GradingApp/Models/Professors.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GradingApp.Models
{
    public class Professors
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int afm { get; set; }

        [Required]
        public string name { get; set; }

        [Required]
        public string surname { get; set; }

        [Required]
        public string department { get; set; }

        [ForeignKey("Users")]
        public string username { get; set; }
        public virtual Users Users { get; set; }
    }
}

GradingApp/Controllers/ProfessorsController.cs
using GradingApp.Data;
using GradingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GradingApp.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly ApplicationDBContext _db;
        public ProfessorsController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult TeacherHomepage(string Username)
        {
            ViewBag.Username = Username;
            return View("TeacherHomepage");
        }
        public async Task<IActionResult> GradesList(string Username, string SemesterNum, string searchString)
        {
            ViewBag.Course = _db.Course.ToList();
            ViewBag.Students = _db.Students.ToList();
            ViewBag.Professors = _db.Professors.ToList();
            ViewBag.CourseHasStudents = _db.CourseHasStudents.ToList();
            ViewBag.Username = Username;
            var crs = from c in _db.CourseHasStudents
                      select c;

            if (!String.IsNullOrEmpty(SemesterNum))
            {
                crs = crs.Where(s => s.Course.courseSemester.ToString() == SemesterNum);
            }
            else
            {
                crs = from c in _db.CourseHasStudents
                      select c;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                crs = crs.Where(s => s.Course.courseTitle!.Contains(searchString));
            }


            return View(await crs.ToListAsync());
        }

        public async Task<IActionResult> EnterGrades(string Username, string SemesterNum, string searchString)
        {
            ViewBag.Course = _db.Course.ToList();
            ViewBag.Students = _db.Students.ToList();
            ViewBag.Professors = _db.Professors.ToList();
            ViewBag.CourseHasStudents = _db.CourseHasStudents.ToList();
            ViewBag.Username = Username;
            var crs = from c in _db.CourseHasStudents
                      select c;

            if (!String.IsNullOrEmpty(SemesterNum))
            {
                crs = crs.Where(s => s.Course.courseSemester.ToString() == SemesterNum);
            }
            else
            {
                crs = from c in _db.CourseHasStudents
                      select c;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                crs = crs.Where(s => s.Course.courseTitle!.Contains(searchString));
            }


            return View(await crs.ToListAsync());
        }

        public IActionResult SubmitGrade(string Username, string SemesterNum, string searchString)
        {
            ViewBag.Username = Username;
            ViewBag.Course = _db.Course.ToList();
            ViewBag.Students = _db.Students.ToList();
            ViewBag.Professors = _db.Professors.ToList();
            ViewBag.CourseHasStudents = _db.CourseHasStudents.ToList();

            int x = Int32.Parse(Request.Form["regnum"].ToString());
            int y = Int32.Parse(Request.Form["cid"].ToString());
            CourseHasStudents chs = _db.CourseHasStudents.ToList().First(chs => chs.registrationNumber == x && chs.idCourse == y);
            chs.grade = Int32.Parse(Request.Form["gradeInput"].ToString());
            _db.CourseHasStudents.Update(chs);
            _db.SaveChanges();
            
            var crs = from c in _db.CourseHasStudents
                      select c;

            if (!String.IsNullOrEmpty(SemesterNum))
            {
                crs = crs.Where(s => s.Course.courseSemester.ToString() == SemesterNum);
            }
            else
            {
                crs = from c in _db.CourseHasStudents
                      select c;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                crs = crs.Where(s => s.Course.courseTitle!.Contains(searchString));
            }

            return View("EnterGrades", crs.ToList());
        }

        public IActionResult Profile(string Username)
        {
            ViewBag.Professor = _db.Professors.ToList().First(s => s.username == Username);

            ViewBag.Users = _db.Users.ToList().First(s => s.username == Username);
            ViewBag.Username = Username;
            return View("Profile");
        }
    }
}

GradingApp/Views/Professors/EnterGrades.cshtml
@model List<GradingApp.Models.CourseHasStudents>
@{
    ViewData["Title"] = "EnterGrades";

}
@section Styles{
    <link rel="stylesheet" href="~/css/MenuStyle.css" />
    <link rel="stylesheet" href="~/css/EnterGradesStyle.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

<section>
    <div class="page">
        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/teacher_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <!--Section of menu's options-->
            <div class="options">
                <a asp-controller="Professors" asp-action="TeacherHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">
                    My Grading
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Professors" asp-action="GradesList" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/card.png")" alt="User" class="icons">Graded Courses</a>
                    <a asp-controller="Professors" asp-action="EnterGrades" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/pending.png")" alt="User" class="icons">Submit grades</a>

                </div>
                <a asp-controller="Professors" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>

        </div>
        <!--END OF MENU-->

        <input type="hidden" name="Username" value="@ViewBag.Username" />

        <div class="main_content">

            <div class="top">
                <h2>My Courses</h2>

            </div>

            <div class="courses">
                <div class="search">

                    <form asp-controller="Professors" asp-action="EnterGrades" method="get">
                        <div class="select">

                            <select id="SemesterNum" name="SemesterNum">
                                <option value="">All</option>
                                <option value="1">Semester 1</option>
                                <option value="2">Semester 2</option>
                                <option value="3">Semester 3</option>
                                <option value="4">Semester 4</option>
                            </select>
                            <input class="btn" type="image" src="~/images/search.png" value="" />
                        </div>


                        <div class="bar">
                            <input class="input" type="text" name="SearchString" placeholder="Search a subject" />
                            <input class="btn" type="image" src="~/images/search.png" value="" />
                        </div>

                    <input type="hidden" name="Username" value="@ViewBag.Username" />
            </form>
            </div>

            @{
                List<int> s = new List<int>();
            }
            @foreach (CourseHasStudents c in Model)
            {
                @if (c.Course.Professors.username == @ViewBag.Username && !s.Contains(c.idCourse))
                {
                    <div class="course">
                            <div class="course_title">
                                <h3>
                                    @c.Course.courseTitle
                                </h3>
                            </div>
                            <div class="course_info">
                   
                                <h4>
                                    Semester @c.Course.courseSemester
                                </h4>
                                <table class="table table-bordered table-stripped">
                                    <thead>
                                        <tr>
                                            <th>
                                                <p>Registration Number</p>
                                            </th>
                                            <th>
                                                Full Name
                                            </th>
                                            <th >
                                                Enter Grade
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                            int counter = 0;
                                        }
                                        @foreach (CourseHasStudents chs in Model)
                                        {
                                            
                                            @if (c.idCourse == chs.idCourse && chs.grade < 0)
                                            {
                                                <tr class="row">
                                                    <td>
                                                        <p>@Html.DisplayFor(modelItem => chs.Students.registressionNumber)</p>

                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => chs.Students.name) @Html.DisplayFor(modelItem => chs.Students.surname)
                                                    </td>
                                                    <td>
                                                        <form asp-controller="Professors" asp-action="SubmitGrade" asp-route-username="@ViewBag.Username" method="post" class="entergrade">
                                                            <input type="number" min="0" max="10" name="gradeInput" class="grade_input"/>
                                                            <input type="hidden" name="regnum" value="@chs.registrationNumber" />
                                                            <input type="hidden" name="cid" value="@chs.idCourse" />
                                                            <input type="submit" value="Submit" class="btn" />
                                                        </form>

                                                    </td>
                                                </tr>

                                                counter++;
                                            }
                                        }

                                        @if (counter == 0)
                                        {
                                             <tr class="row">
                                                <td class="empty">
                                                    <img src="@Url.Content("~/images/not_found.png")" alt="User" class="icons">No pending grades
                                                </td>
                                             </tr>
                                        }


                                    </tbody>

                                </table>
                    </div>
                    </div>
                    s.Add(c.idCourse);
                }

                }
            </div>

        </div>
    </div>


    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</section>

GradingApp/Views/Professors/GradesList.cshtml
@model List<GradingApp.Models.CourseHasStudents>
@{
    ViewData["Title"] = "GradesList";

}
@section Styles{
    <link rel="stylesheet" href="~/css/MenuStyle.css" />
    <link rel="stylesheet" href="~/css/GradesListStyle.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}
<section>
    <div class="page">

        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/teacher_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <!--Section of menu's options-->
            <div class="options">
                <a asp-controller="Professors" asp-action="TeacherHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">
                    My Grading
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Professors" asp-action="GradesList" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/card.png")" alt="User" class="icons">Graded Courses</a>
                    <a asp-controller="Professors" asp-action="EnterGrades" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/pending.png")" alt="User" class="icons">Submit grades</a>

                </div>
                <a asp-controller="Professors" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>

        </div>

        <div class="main_content">
            <div class="top">
                <h2>My Courses</h2>

            </div>
            <div class="courses">
                <div class="search">
                <form asp-controller="Professors" asp-action="GradesList" method="get">
                        
                        <div class="select">
                            <select id="SemesterNum" name="SemesterNum">
                                <option value="">All</option>
                                <option value="1">Semester 1</option>
                                <option value="2">Semester 2</option>
                                <option value="3">Semester 3</option>
                                <option value="4">Semester 4</option>
                            </select>
                            <input class="btn" type="image" src="~/images/search.png" value="" />

                        </div>
                      

                           <div class="bar">
                               <input class="input" type="text" name="SearchString" placeholder="Search a subject" />
                                <input class="btn" type="image" src="~/images/search.png" value="" />

                            </div>
                       
                         <input type="hidden" name="Username" value="@ViewBag.Username" />

                    </form>

                </div>
                
                   
                @{
                    List<int> s = new List<int>();
                }
                
                @foreach (CourseHasStudents c in Model)
                {   
                    
                    @if (c.Course.Professors.username == @ViewBag.Username && !s.Contains(c.idCourse))
                    {
                        <div class="course">
                            <div class="course_title">
                                <h3>
                                    @c.Course.courseTitle
                                </h3>

                            </div>
                            <div class="course_info">

                                <h4>
                                    Semester @c.Course.courseSemester
                                </h4>
                                <table class="table table-bordered table-stripped">
                                    <thead>
                                        <tr>
                                            <th>
                                                <p>Registration Number</p>
                                            </th>
                                            <th>
                                                Full Name
                                            </th>
                                            <th>
                                                Grade
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (CourseHasStudents chs in Model)
                                        {
                                            @if (c.idCourse == chs.idCourse && chs.grade >= 0)
                                            {
                                                <tr class="row">
                                                    <td>
                                                        <p>@Html.DisplayFor(modelItem => chs.Students.registressionNumber)</p>

                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => chs.Students.name) @Html.DisplayFor(modelItem => chs.Students.surname)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => chs.grade)
                                                    </td>
                                                </tr>
                                            }
                                        }


                                    </tbody>

                                </table>


                            </div>

                     
                        </div>
                        s.Add(c.idCourse);
                    }


                }
            </div>
        </div>

    </div>


    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</section>

GradingApp/Views/Professors/Profile.cshtml
@model List<GradingApp.Models.Professors>
@{
    ViewData["Title"] = "Profile";
}
@section Styles{
    <link rel="stylesheet" href="~/css/MenuStyle.css" />
    <link rel="stylesheet" href="~/css/TeacherProfileStyle.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

<section>
    <div class="page">
        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/teacher_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <!--Section of menu's options-->
            <div class="options">
                <a asp-controller="Professors" asp-action="TeacherHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">
                    My Grading
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Professors" asp-action="GradesList" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/card.png")" alt="User" class="icons">Graded Courses</a>
                    <a asp-controller="Professors" asp-action="EnterGrades" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/pending.png")" alt="User" class="icons">Submit grades</a>

                </div>
                <a asp-controller="Professors" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>

        </div>
        <!--END OF SIDE MENU-->
        <!--MAIN CONTENT-->

        <div class="main_content">
            <div class="top">
                <h2>Profile Information</h2>
            </div>

            <div class="info">
                <div class="profile">
                    <div class="card_title">
                        <h3>
                            @ViewBag.Professor.name @ViewBag.Professor.surname's Card

                        </h3>
                    </div>
                    <picture>
                        <img src="@Url.Content("~/images/teacher_symbol.png")" alt="User" class="icons">
                    </picture>
                    <table>
                        <tr>
                            <td class="title">
                                AFM
                            </td>
                            <td>
                                @ViewBag.Professor.afm
                            </td>
                        </tr>
                        <tr>
                            <td class="title">
                                Username
                            </td>
                            <td>
                                @ViewBag.Professor.username
                            </td>
                        </tr>
                        <tr>
                            <td class="title">
                                Password
                            </td>
                            <td>
                                @ViewBag.Professor.Users.password
                            </td>
                        </tr>
                        <tr>
                            <td class="title">
                                Name
                            </td>
                            <td>
                                @ViewBag.Professor.name
                            </td>
                        </tr>
                        <tr>
                            <td class="title">
                                Surname
                            </td>
                            <td>
                                @ViewBag.Professor.surname
                            </td>
                        </tr>
                        <tr>
                            <td class="title">
                                Department
                            </td>
                            <td>
                                @ViewBag.Professor.department
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="image">
                    <img src="@Url.Content("~/images/profile.png")" alt="User" class="icons">

                </div>

            </div>
            
        </div>
        </div>
    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</section>