GradingApp/Controllers/SecretariesController.cs
using GradingApp.Data;
using Microsoft.AspNetCore.Mvc;
using GradingApp.Models;
using Microsoft.EntityFrameworkCore;

namespace GradingApp.Controllers
{
    public class SecretariesController : Controller
    {
        private readonly ApplicationDBContext _db;
        public SecretariesController(ApplicationDBContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Registration(string Username)
        {
            ViewBag.Username = Username;
            return View("Registration");
        }
        public async Task<IActionResult> AssignCourse(string Username) 
        {
            ViewBag.Username = Username;
            ViewBag.Professors = _db.Professors.ToList();
            var crs = from c in _db.Course
                      select c;
            return View(await crs.ToListAsync());
        }
        public IActionResult AllCourses(string Username)
        {
            ViewBag.Course = _db.Course.ToList();
            ViewBag.Students = _db.Students.ToList();
            ViewBag.Professors = _db.Professors.ToList();
            ViewBag.CourseHasStudents = _db.CourseHasStudents.ToList();
            ViewBag.Username = Username;
            if (_db.Course == null)
            {
                return Problem("Entity set 'ApplicationDBContext.Course'  is null.");
            }

            return View("AllCourses");
        }

        public IActionResult RegisterUser() {
            
            Users u = new Users();
            u.username = Request.Form["username"].ToString();
            u.password = Request.Form["password"].ToString();
            if (Request.Form["radio"].ToString() == "professor")
            {
                Professors p = new Professors();
                p.name = Request.Form["name"].ToString();
                p.surname = Request.Form["surname"].ToString();
                p.department = Request.Form["department"].ToString();
                p.afm = Int32.Parse(Request.Form["code"].ToString());
                p.username = Request.Form["username"].ToString();
                u.role = "professor";
                _db.Users.Add(u);
                _db.Professors.Add(p);
            }
            else if (Request.Form["radio"].ToString() == "student")
            {
                Students s = new Students();
                s.name = Request.Form["name"].ToString();
                s.surname = Request.Form["surname"].ToString();
                s.department = Request.Form["department"].ToString();
                s.registressionNumber = Int32.Parse(Request.Form["code"].ToString());
                s.username = Request.Form["username"].ToString();
                u.role = "student";
                _db.Users.Add(u);
                _db.Students.Add(s);        
            }
            else
            {
                
            }
            _db.SaveChanges();
            return View("Registration");
        }
        public IActionResult RegisterCourse()
        {
            Course c = new Course();
            c.afm = -1;
            c.courseTitle = Request.Form["title"].ToString();
            c.courseSemester = Int32.Parse(Request.Form["semester"].ToString());
            _db.Course.Add(c);
            _db.SaveChanges();
            return View("Registration");
        }

        public IActionResult AssignProfessor(string username)
        {
            ViewBag.Username = username;
            ViewBag.Professors = _db.Professors.ToList();
            int x = Int32.Parse(Request.Form["course"].ToString());
            Course c = _db.Course.ToList().First(c => c.idCourse == x);
            c.afm = Int32.Parse(Request.Form["professor"].ToString());
            _db.Course.Update(c);
            _db.SaveChanges();
            var crs = from i in _db.Course
                      select i;
            return View("AssignCourse", crs.ToList());
        }

        public IActionResult AssignStudent(string username)
        {
            ViewBag.Username = username;
            ViewBag.Professors = _db.Professors.ToList();
            CourseHasStudents chs = new CourseHasStudents();
            chs.idCourse = Int32.Parse(Request.Form["course_student"].ToString());
            chs.registrationNumber = Int32.Parse(Request.Form["student"].ToString());
            chs.grade = -1;
            _db.CourseHasStudents.Add(chs);
            _db.SaveChanges();
            var crs = from c in _db.Course
                      select c;
            return View("AssignCourse", crs.ToList());
        }

        public IActionResult Profile(string Username)
        {
            ViewBag.Secretary = _db.Secretaries.ToList().First(s => s.username == Username);

            ViewBag.Users = _db.Users.ToList().First(s => s.username == Username);
            ViewBag.Username = Username;
            return View("Profile");
        }
        public IActionResult SecretaryHomepage(string Username)
        {
            ViewBag.Username = Username;
            return View("SecretaryHomepage");
        }
    }
}

GradingApp/Views/Secretaries/AllCourses.cshtml
@{
    ViewData["Title"] = "AssignCourse";

}
@section Styles{
                <link rel="stylesheet" href="~/css/MenuStyle.css" />
                <link rel="stylesheet" href="~/css/AllCoursesStyle.css" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

<section>
    <!--Section of the side navigation menu-->

    <div class="page">

        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/secr_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <div class="options">
                <a asp-controller="Secretaries" asp-action="SecretaryHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <!--DROPDOWN-->
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/student_icon.png")" alt="User" class="icons">
                    Student
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/teacher.png")" alt="User" class="icons">
                    Teacher
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>

                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/courses.png")" alt="User" class="icons">
                    Courses
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/add_course.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AllCourses" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">Overview</a>

                </div>

                <a hasp-controller="Secretaries" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>
        </div>
        <!--END OF MENU-->

        <div class="main_content">
            <div class="top">
                <h2>Overview</h2>

            </div>
            <div class="courses">
                <div class="container">
                    <div class="courses_title">
                        <h3>Available Courses  </h3>

                    </div>
                    <table class="table table-bordered table-stripped">
                        <thead>
                            <tr>
                                <th>Subject</th>
                                <th>Semester</th>
                                <th>Professor</th>
                                <th>Number of Registered students </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (Course c in @ViewBag.Course)
                            {
                                int count = 0;
                                @foreach (CourseHasStudents chs in @ViewBag.CourseHasStudents)
                                {

                                    @if (c.idCourse == chs.idCourse)
                                    {
                                        count++;
                                    }
                                }
                                <tr class="row">
                                    <td class="title">
                                        @c.courseTitle
                                    </td>
                                    <td align="center">
                                        @c.courseSemester
                                    </td>
                                    <td align="center">
                                        @c.Professors.surname @c.Professors.name
                                    </td>
                                    <td align="center">
                                        @count
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
                
            </div>
          
        </div>
    </div>


  
                


    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>

</section>

GradingApp/Views/Secretaries/AssignCourse.cshtml
@model List<GradingApp.Models.Course>
@{
    ViewData["Title"] = "AssignCourse";

}
@section Styles{
            <link rel="stylesheet" href="~/css/MenuStyle.css" />
            <link rel="stylesheet" href="~/css/AssignCourseStyle.css" />
            <script type="text/javascript" src="~/js/AssignmentSuccessScript.js">    </script>

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}
<section>
    <!--Section of the side navigation menu-->

    <div class="page">

        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/secr_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <div class="options">
                <a asp-controller="Secretaries" asp-action="SecretaryHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <!--DROPDOWN-->
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/student_icon.png")" alt="User" class="icons">
                    Student
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/teacher.png")" alt="User" class="icons">
                    Teacher
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>

                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/courses.png")" alt="User" class="icons">
                    Courses
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/add_course.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AllCourses" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">Overview</a>

                </div>

                <a hasp-controller="Secretaries" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>
        </div>
        <!--END OF MENU-->

        <input type="hidden" name="Username" value="@ViewBag.Username" />

        <div class="main_content">
            <!--LEFT SECTION OF CONTAINER-->
            <div class="left">
                <!--UPPER FORM-->
                <div class="form">
                    <h2>Student Assigning  </h2>
                    <form asp-controller="Secretaries" asp-action="AssignStudent" asp-route-username="@ViewBag.Username">
                        <h4>Assign a student to one of the courses available!</h4>

                        <!--Ragistration number-->
                        <div class="form-group">
                            <input class="form-control" placeholder="Registration Number of student" name="student"/>
                            <span class="text-danger"></span> <!--Used if the user has entered wrong details on this input-->
                        </div>
                        <!--Course selection-->
                        <div class="form-group">
                            <select class="list" name="course_student">
                                @foreach (Course c in Model)
                                {
                                    <option value="@c.idCourse">
                                        @Html.DisplayFor(modelItem => c.courseTitle)
                                    </option>
                                }

                            </select>
                            <span class="text-danger"></span> <!--Used if the user has entered wrong details on this input-->
                        </div>

                        <input type="submit" value="Add" class="btn btn-primary" onclick="success_student()" />

                    </form>
                </div>

                <!--DOWN FORM-->
                <div class="form">
                    <h2>Professor Assigning  </h2>
                    <form asp-controller="Secretaries" asp-action="AssignProfessor" asp-route-username="@ViewBag.Username">
                        <h4>Assign a professor to one of the courses available!</h4>

                        <!--Professor selection-->
                        <div class="form-group">
                            <select class="list" name="professor">
                                @foreach (Professors p in ViewBag.Professors)
                                {
                                    @if (p.afm != -1)
                                    {
                                        <option value="@p.afm">
                                            @p.surname @p.name
                                        </option>
                                    }
                                    
                                }
                            </select>
                            <span class="text-danger"></span> <!--Used if the user has entered wrong details on this input-->
                        </div>
                        <!--Course selection-->
                        <div class="form-group">
                            <select class="list" name="course">
                                @foreach (Course c in Model)
                                {
                                    <option value="@c.idCourse">
                                        @Html.DisplayFor(modelItem => c.courseTitle)
                                    </option>
                                }
                            </select>
                            <span class="text-danger"></span> <!--Used if the user has entered wrong details on this input-->
                        </div>

                        <input type="submit" value="Add" class="btn btn-primary" onclick="success_professor()" />

                    </form>
                </div>


            </div>

            <!--RIGHT SECTION OF CONTAINER-->
            <div class="right">

                <div class="title">
                    <h1>Only 2 steps away!</h1>
                </div>
                <img src="@Url.Content("~/images/man.png")" alt="User" class="icons">

            </div>
            

        </div>

        </div>
    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</section>

GradingApp/Views/Secretaries/Profile.cshtml
@model List<GradingApp.Models.Secretaries>
@{
    ViewData["Title"] = "Profile";
}
@section Styles{
    <link rel="stylesheet" href="~/css/MenuStyle.css" />
    <link rel="stylesheet" href="~/css/TeacherProfileStyle.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}

<section>
    <div class="page">
        <!--Section of the side navigation menu-->
        <div class="sidenav">

            <!--Section of image-->
            <div class="profile_image">
                <picture>
                    <img src="@Url.Content("~/images/secr_symbol.png")" alt="User" class="icons">
                </picture>
            </div>

            <div class="options">
                <a asp-controller="Secretaries" asp-action="SecretaryHomepage" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/home.png")" alt="User" class="icons">
                    Homepage
                </a>
                <!--DROPDOWN-->
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/student_icon.png")" alt="User" class="icons">
                    Student
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>
                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/teacher.png")" alt="User" class="icons">
                    Teacher
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/register.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AssignCourse" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/assign.png")" alt="User" class="icons">Assign Course</a>
                </div>

                <button class="dropdown-btn">
                    <img src="@Url.Content("~/images/courses.png")" alt="User" class="icons">
                    Courses
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a asp-controller="Secretaries" asp-action="Registration" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/add_course.png")" alt="User" class="icons">Register</a>
                    <a asp-controller="Secretaries" asp-action="AllCourses" asp-route-username="@ViewBag.Username"><img src="@Url.Content("~/images/grade.png")" alt="User" class="icons">Overview</a>

                </div>

                <a hasp-controller="Secretaries" asp-action="Profile" asp-route-username="@ViewBag.Username">
                    <img src="@Url.Content("~/images/user_green.png")" alt="User" class="icons">
                    Profile
                </a>
                <a class="logout" asp-controller="Home" asp-action="Login">
                    <img src="@Url.Content("~/images/logout.png")" alt="User" class="icons">Logout
                </a>
            </div>
        </div>
        <!--END OF SIDE MENU-->
        <!--MAIN CONTENT-->

        <div class="main_content">
            <div class="top">
                <h2>Profile Information</h2>
            </div>
            <div class="info">
                <div class="profile">
                    <div class="card_title">
                        <h3>
                            @ViewBag.Secretary.name @ViewBag.Secretary.surname's Card

                        </h3>
                    </div>
                    <picture>
                        <img src="@Url.Content("~/images/secr_symbol.png")" alt="User" class="icons">
                    </picture>
            <table>
                <tr>
                            <td class="title">
                        Phone Number
                    </td>
                    <td>
                        @ViewBag.Secretary.phoneNumber
                    </td>
                </tr>
                <tr>
                            <td class="title">
                        Username
                    </td>
                    <td>
                        @ViewBag.Secretary.username
                    </td>
                </tr>
                <tr>
                            <td class="title">
                        Password
                    </td>
                    <td>
                        @ViewBag.Secretary.Users.password
                    </td>
                </tr>
                <tr>
                            <td class="title">
                        Name
                    </td>
                    <td>
                        @ViewBag.Secretary.name
                    </td>
                </tr>
                <tr>
                            <td class="title">
                        Surname
                    </td>
                    <td>
                        @ViewBag.Secretary.surname
                    </td>
                </tr>
                <tr>
                            <td class="title">
                        Department
                    </td>
                    <td>
                        @ViewBag.Secretary.department
                    </td>
                </tr>
            </table>
            </div>
                <div class="image">
                    <img src="@Url.Content("~/images/profile.png")" alt="User" class="icons">

                </div>
        </div>
        </div>
        </div>

    <script>
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</section>